import java.util.List;

// Sealed parent entity
// A sealed interface restricts which classes or records can implement it.
// Only User and AuditInfo are allowed.
sealed interface Entity permits User, AuditInfo { }


// Generic record
// Records automatically create final fields, constructor, getters, equals, hashCode, toString.
// This record represents simple audit info.
record AuditInfo<T>(T createdBy, long createdAt) implements Entity { }


// User record demonstrating many features of records
record User(
        int id,
        String name,
        Address addr,
        List<Role> roles,
        AuditInfo<String> ainfo
) implements Entity {

    // Nested record inside User
    // Represents user address immutably.
    record Address(String city, String country) { }

    // Enum declared inside User
    // Roles represent what user can do.
    enum Role { USER, MANAGER, ADMIN }

    // Static field
    // Used for validation inside compact constructor.
    static int minNameLength = 3;

    // Static factory method
    // Creates a default user.
    static User getUser() {
        return new User(
                0,
                "guest",
                new Address("abc", "def"),
                List.of(Role.USER),
                new AuditInfo<>("system", System.currentTimeMillis())
        );
    }

    // Compact constructor
    // Automatically receives constructor parameters.
    // Used for validation and setting up immutable fields properly.
    User {
        if (name == null || name.length() < minNameLength) {
            throw new IllegalArgumentException("name too short");
        }
        if (roles == null || roles.isEmpty()) {
            throw new IllegalArgumentException("User must have at least one role");
        }

        // Enforce immutability of list (records are immutable but list is not)
        roles = List.copyOf(roles);
    }

    // Custom method inside record
    // Records can contain methods just like classes.
    boolean isAdmin() {
        return roles.contains(Role.ADMIN);
    }
}



public class code15_records {
    public static void main(String[] args) {

        // Creating a User object using the canonical constructor autogenerated by the record.
        User u = new User(
                1,
                "prateek",
                new User.Address("abc", "xyz"),
                List.of(User.Role.ADMIN, User.Role.MANAGER),
                new AuditInfo<>("temp_user", System.currentTimeMillis())
        );

        // Accessing auto-generated accessor methods
        System.out.println(u.name());            // prints "prateek"
        System.out.println(u.addr().city());     // prints "abc"
        System.out.println(u.isAdmin());         // true

        // Using static factory method
        User guest = User.getUser();
        System.out.println(guest);

        // Using record objects inside streams
        List<User> users = List.of(u, guest);

        users.stream()
                .filter(User::isAdmin)          // method reference
                .forEach(System.out::println);

        // Using generic record
        AuditInfo<Integer> audit = new AuditInfo<>(100, System.currentTimeMillis());
        System.out.println(audit);
    }
}
